carex/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Carex Administration"
admin.site.site_title = "Carex Admin Portal"
admin.site.index_title = "Welcome to Carex Admin Portal"

web/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("services/", views.services, name="services"),
    path('service_details/<slug>/',views.service_detail,name='service_detail'),
    path("blog/", views.blog, name="blog"),
    path('blog/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path("contact/", views.contact, name="contact"),
    path('pricing/',views.pricing,name='pricing'),
    path('team/<slug:slug>/', views.team_detail, name='team_detail'),
    path("enquery/", views.enquery, name="enquery"),
]

templates/web/partials/footer.html
{% load static %}
<section class="appointment">
    <div class="background bg-img bg-fixed section-padding pb-0" data-background="{% static 'web/img/slider/2.jpg' %}" data-overlay-dark="5">
        <div class="container">
            <div class="row">
                <!-- Appointment -->
                <div class="col-md-5 mb-30 mt-60">
                    <div class="ready mb-20">
                        <h5>Book Now</h5>
                        <h4>Make Your Appointment</h4>
                        <p>Get special repaire service for your car from our experts with appointmet and win car wash Free.</p>
                    </div>
                    <div class="help">
                        <div class="icon color-1"><span class="carex-phone-call"></span></div>
                        <div class="text">
                            <p class="color-1">Need Any Help?</p> <a class="color-1" href="tel:855-100-4444">855 100 4444</a>
                        </div>
                    </div>
                </div>
                <!-- Booking From -->
                <div class="col-md-6 offset-md-1">
                    <div class="booking-box">
                        <div class="head-box mb-30">
                            <h5>Appointment</h5>
                            <h4>Book For A Service</h4>
                        </div>
                        <div class="booking-inner clearfix">
                            <form action="{% url 'web:enquery' %}" class="form1 clearfix ajax reload" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="input1_wrapper">
                                            <label>Your Name</label>
                                            <div class="input2_inner">
                                                {{bookingform.name}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="input1_wrapper">
                                            <label>Your Phone</label>
                                            <div class="input2_inner">
                                                {{bookingform.phone}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="input1_wrapper">
                                            <label>Service Date</label>
                                            <div class="input1_inner">
                                                {{bookingform.service_date}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="select1_wrapper">
                                            <label>Service Time</label>
                                            <div class="select1_inner">
                                                {{bookingform.service_time}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="select1_wrapper">
                                            <label>Select A Service</label>
                                            <div class="select1_inner">
                                                {{bookingform.services}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="select1_wrapper">
                                            <label>Service Master</label>
                                            <div class="select1_inner">
                                                {{bookingform.service_master}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <button type="submit" class="btn-form1-submit mt-15">Book Now</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Clients -->
<section class="clients">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="owl-carousel owl-theme">
                    <div class="clients-logo">
                        <a href="#0"><img src="{% static 'web/img/clients/1.png' %}" alt=""></a>
                    </div>
                    <div class="clients-logo">
                        <a href="#0"><img src="{% static 'web/img/clients/2.png' %}" alt=""></a>
                    </div>
                    <div class="clients-logo">
                        <a href="#0"><img src="{% static 'web/img/clients/3.png' %}" alt=""></a>
                    </div>
                    <div class="clients-logo">
                        <a href="#0"><img src="{% static 'web/img/clients/4.png' %}" alt=""></a>
                    </div>
                    <div class="clients-logo">
                        <a href="#0"><img src="{% static 'web/img/clients/5.png' %}" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Footer -->
<footer class="footer clearfix">
    <div class="container">
        <!-- first footer -->
        <div class="first-footer">
            <div class="row">
                <div class="col-md-12">
                    <div class="links dark footer-contact-links">
                        <div class="footer-contact-links-wrapper">
                            <div class="footer-contact-link-wrapper">
                                <div class="image-wrapper footer-contact-link-icon">
                                    <div class="icon-footer"> <i class="carex-phone-call"></i> </div>
                                </div>
                                <div class="footer-contact-link-content">
                                    <h6>Call us</h6>
                                    <p>855 100 4444</p>
                                </div>
                            </div>
                            <div class="footer-contact-links-divider"></div>
                            <div class="footer-contact-link-wrapper">
                                <div class="image-wrapper footer-contact-link-icon">
                                    <div class="icon-footer"> <i class="carex-email"></i> </div>
                                </div>
                                <div class="footer-contact-link-content">
                                    <h6>Write to us</h6>
                                    <p>info@carex.com</p>
                                </div>
                            </div>
                            <div class="footer-contact-links-divider"></div>
                            <div class="footer-contact-link-wrapper">
                                <div class="image-wrapper footer-contact-link-icon">
                                    <div class="icon-footer"> <i class="carex-location-map"></i> </div>
                                </div>
                                <div class="footer-contact-link-content">
                                    <h6>Address</h6>
                                    <p>24 King St, SC 29401 USA</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- second footer -->
        <div class="second-footer">
            <div class="row">
                <!-- about & social icons -->
                <div class="col-md-4 widget-area">
                    <div class="widget clearfix">
                        <div class="footer-logo"><img src="img/logo-light.png" alt=""></div>
                        <!-- <div class="footer-logo"><h2>CARE<span>X</span></h2></div> -->
                        <div class="widget-text">
                            <p>Carex imperdiet sapien porttito the bibenum ellentesue the commodo erat nesuen.</p>
                            <div class="social-icons">
                                <ul class="list-inline">
                                    <li><a href="#"><i class="fa fa-whatsapp"></i></a></li>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- quick links -->
                <div class="col-md-3 offset-md-1 widget-area">
                    <div class="widget clearfix usful-links">
                        <h3 class="widget-title">Quick Links</h3>
                        <ul>
                            <li><a href="about.html">About</a></li>
                            <li><a href="services.html">Services</a></li>
                            <li><a href="pricing.html">Pricing</a></li>
                            <li><a href="team.html">Team</a></li>
                        </ul>
                    </div>
                </div>
                <!-- subscribe -->
                <div class="col-md-4 widget-area">
                    <div class="widget clearfix">
                        <h3 class="widget-title">Subscribe</h3>
                        <p>Want to be notified about our services. Just sign up and we'll send you a notification by email.</p>
                        <div class="widget-newsletter">
                            <form action="#">
                                <input type="email" placeholder="Email Address" required>
                                <button type="submit">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- bottom footer -->
        <div class="bottom-footer-text">
            <div class="row copyright">
                <div class="col-md-12">
                    <p class="mb-0">&copy;2024 <a href="#">Adhi</a>. All rights reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/web/partials/header.html
   {% load static %}
   
   <!-- Navbar -->
   <nav class="navbar navbar-expand-lg">
    <div class="container">
        <!-- Logo -->
        <div class="logo-wrapper">
            <a class="logo" href="index.html"> <img src="{% static 'web/img/logo-light.png' %}" class="logo-img" alt=""> </a>
            <!-- <a class="logo" href="index.html"> <h2>CARE<span>X</span></h2> </a> -->
        </div>
        <!-- Button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"><i class="fa fa-bars"></i></span> </button>
        <!-- Menu -->
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'web:index' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'web:about' %}">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'web:services' %}">Services</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'web:blog' %}">Blog</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'web:contact' %}">Contact</a></li>
            </ul>
            <div class="navbar-right">
                <div class="wrap">
                    <div class="icon"> <i class="carex-phone-call"></i> </div>
                    <div class="text">
                        <p>Need help?</p>
                        <h5><a href="tel:8551004444">855 100 4444</a></h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>